version: '3.8'

services:
  db:
    image: postgres
    container_name: supplier-db
    environment:
      POSTGRES_USER: admin # в открытом виде для быстрого тестового развертывания
      POSTGRES_PASSWORD: admin # в открытом виде для быстрого тестового развертывания
      POSTGRES_DB: supplier_db # в открытом виде для быстрого тестового развертывания
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: supplier-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/supplier_db
      SPRING_DATASOURCE_USERNAME: admin # в открытом виде для быстрого тестового развертывания
      SPRING_DATASOURCE_PASSWORD: admin # в открытом виде для быстрого тестового развертывания
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "80:80"

volumes:
  postgres_data:
